# Use Python 3.7 as the base image
FROM python:3.7-slim

# Set the working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .
EXPOSE 8084
# Run the application
CMD ["python", "main.py"]